consumes:
- application/json
definitions:
  PostTopicPayload:
    example:
      content: 4njw3zeoyp
      userName: Laudantium quaerat nihil voluptates dolorem.
    properties:
      content:
        description: Content of the topic
        example: 4njw3zeoyp
        maxLength: 255
        type: string
      userName:
        description: Author of this topic
        example: Laudantium quaerat nihil voluptates dolorem.
        type: string
    required:
    - content
    - userName
    title: PostTopicPayload
    type: object
  RegisterUserPayload:
    example:
      country: Recusandae voluptatem.
      name: Porro ipsum voluptatem aut.
      password: Veniam accusamus quasi placeat quasi.
    properties:
      country:
        description: country of the user
        example: Recusandae voluptatem.
        type: string
      name:
        description: username
        example: Porro ipsum voluptatem aut.
        type: string
      password:
        description: password of the user
        example: Veniam accusamus quasi placeat quasi.
        type: string
    required:
    - name
    - password
    - country
    title: RegisterUserPayload
    type: object
  VoteTopicPayload:
    example:
      userName: Officiis qui iste et eveniet ut qui.
      vote: down
    properties:
      userName:
        description: username
        example: Officiis qui iste et eveniet ut qui.
        type: string
      vote:
        description: upvote/downvote topic
        enum:
        - up
        - down
        example: down
        type: string
    required:
    - userName
    - vote
    title: VoteTopicPayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609066e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609066e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
info:
  description: Carousell Challenge.
  title: Carousell Challenge
  version: "0.1"
paths:
  /{filepath}:
    get:
      operationId: public#/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      - https
      summary: Download public/
  /api/v1/topics:
    get:
      description: Show top topics
      operationId: topic#show
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      - https
      summary: show topic
      tags:
      - topic
    post:
      description: Post new topic
      operationId: topic#post
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/PostTopicPayload'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      - https
      summary: post topic
      tags:
      - topic
  /api/v1/topics/{topicID}:
    patch:
      description: upvote/downvote cluster
      operationId: topic#vote
      parameters:
      - in: path
        name: topicID
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/VoteTopicPayload'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      - https
      summary: vote topic
      tags:
      - topic
  /api/v1/users:
    post:
      description: Register new user
      operationId: user#register
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/RegisterUserPayload'
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      - https
      summary: register user
      tags:
      - user
  /api/v1/users/{userName}:
    delete:
      description: remove user
      operationId: user#remove
      parameters:
      - in: path
        name: userName
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      - https
      summary: remove user
      tags:
      - user
    get:
      description: Login user details by name
      operationId: user#login
      parameters:
      - description: password of the user
        in: query
        name: password
        required: true
        type: string
      - in: path
        name: userName
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      schemes:
      - http
      - https
      summary: login user
      tags:
      - user
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      - https
      summary: Download swagger/swagger.json
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
