// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "carousell-challenge": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/Coding24x7/carousell-challenge/design
// --out=$(GOPATH)/src/github.com/Coding24x7/carousell-challenge
// --version=v1.2.0-dirty

package app

// TopicHref returns the resource href.
func TopicHref() string {
	return "/api/v1/topics"
}
