// Code generated by goagen v1.4.0, DO NOT EDIT.
//
// API "twitter-clone": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/Coding24x7/twitter-clone/design
// --out=$(GOPATH)src/github.com/Coding24x7/twitter-clone
// --version=v1.4.0

package app
